server:
  port: 6002
dubbo:
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848
  protocol:
    name: tri
    port: 50052
  application:
    logger: slf4j
    name: DubboProviderTwoApplication
    qos-enable: false
